apiVersion: v1
kind: Service
metadata:
  name: nb-node-starter
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: nb-node-starter
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nb-node-starter
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: nb-node-starter
    spec:
      containers:
      - name: nb-node-starter
        image: sultansaadat84/nb-node-starter:latest               
        ports:
        - containerPort: 8080